name: build check
on: [pull_request, workflow_dispatch, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - run: pnpm install

      - run: pnpm run build

      - name: lighthouse check
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: 'lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: apps/website/dist/
